### PR TITLE
refreshDynamicVariables before panels processing in console

### PR DESCRIPTION
**Pull request by mmichna**
I added call for method _com.izforge.izpack.installer.base.InstallerBase.refreshDynamicVariables(AutomatedInstallData, VariableSubstitutor...)_ into console installer before panels processing action. {color:blue}NOTE:{color} same principe as in com.izforge.izpack.installer.automation.AutomatedInstaller.doInstall()

### CODE REVIEW

**Comment by mmichna** [comment]
I tested each _DVSK s.r.o_ IzPack consolePanels and several standard IzPack consolePanels
- in our environment we have _Dvsk izpack demo_ and i implemented and tested each console panel helpers from this demo
  *\* IzPack standard panels: TargetPanel. SummaryPanel, InstallPanel and SimpleFinishPanel

```
<panels>
    <panel classname="com.izforge.izpack.panels.target.TargetPanel" />
    <panel classname="com.izforge.izpack.panels.verifyenvironment.VerifyEnvironmentPanel" />
    <panel classname="com.izforge.izpack.panels.applicationserver.ApplicationServerPanel" />
    <panel classname="com.izforge.izpack.panels.connection.ConnectionPanel" />
    <panel classname="com.izforge.izpack.panels.persistencexml.PersistenceXmlPanel" />
    <panel classname="com.izforge.izpack.panels.contextxml.ContextXmlPanel" />
    <panel classname="com.izforge.izpack.panels.schemacreator.SchemaCreatorPanel" />
    <panel classname="com.izforge.izpack.panels.sqlscriptrunner.SqlScriptRunnerPanel" />
    <panel classname="com.izforge.izpack.panels.liquibase.LiquiBasePanel" />
    <panel classname="com.izforge.izpack.panels.summary.SummaryPanel" />
    <panel classname="com.izforge.izpack.panels.install.InstallPanel" />
    <panel classname="com.izforge.izpack.panels.simplefinish.SimpleFinishPanel" />
</panels>
```
- NEXT STEP: test generate properties file and automationHelpers

**Comment by mmichna** [comment]
I tested generation properties file and automation installation from properties file

**Comment by jponge** [comment]
Your diffs match your own coding standards, but they do not match those of the files they are applied on. Nobody will ever agree on good vs bad code format, but a common practice is to blend your changes into the style of existing files ;-)

Would you be able to reformat?

Thanks a lot

**Comment by jponge** [comment]
Hum, the merge with the current `master` branch is not trivial, so I'd rather have you do a rebase and update the pull request instead.

**Pull request closed without merging**
