### PR TITLE
Fix for IZPACK-789 and apply patch from IZPACK-337

### PR DESCRIPTION
**Pull request by thescouser89**

### CODE REVIEW

**Comment by thescouser89** [comment]
By the way are you guys removing all dependencies between packages other than com.izforge.izpack.util/api/core/installer?

It's kind of hard backporting changes from 4.3 branch to master / 5.0 because of that.

**Comment by jponge** [comment]
Could you please respect the original file source code format? ANSI vs K&R style is an endless debate, but keeping things consistent in existing code is best :-)

I'll then happily merge.

Thanks!

**Comment by thescouser89** [comment]
Oh Julien I'm a little bit confused :( I think I only used K&R for the static code part. I left it as ANSI for the rest of my diff.

Do you want me to do something like that?

``` java

   static 
   {
        try
        {
             ...
        }
        catch (SevereException e)
        {
             ...
        }
    }
```

**Comment by jponge** [comment]
Yes exactly. I don't mean to be pedantic, but indeed a good practice is to stick to the surrounding style within the modified source file :-)

**Comment by thescouser89** [comment]
Will close that pull request and will open a new one. And I understand why you want the code to have a consistent style :)

It was my error.

**Pull request closed without merging**
